### ISSUE TITLE
Support for files larger than 1MB

### ISSUE THREAD

**Issue by Razoxane** [benbalter/word_diff#6]
I've successfully created a heroku server, and deployed word_diff to it.
When sending my first payload, I get the following error message in the logs:
```
Octokit::Forbidden: The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.
 Error summary:
   resource: Blob
   field: data
   code: too_large // See: https://developer.github.com/v3/repos/contents/#get-contents:
    /app/vendor/bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
    /app/vendor/bundle/ruby/2.0.0/gems/octokit-3.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
    /app/vendor/bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
    /app/vendor/bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
    /app/vendor/bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
    /app/vendor/bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
    /app/vendor/bundle/ruby/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
    /app/vendor/bundle/ruby/2.0.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
    /app/vendor/bundle/ruby/2.0.0/gems/octokit-3.8.0/lib/octokit/client.rb:339:in `request'
    /app/vendor/bundle/ruby/2.0.0/gems/octokit-3.8.0/lib/octokit/client.rb:135:in `get'
    /app/vendor/bundle/ruby/2.0.0/gems/octokit-3.8.0/lib/octokit/client/contents.rb:35:in `contents'
    /app/lib/word_diff/document.rb:31:in `download'
    /app/lib/word_diff/document.rb:46:in `to_md'
    /app/lib/word_diff/document.rb:75:in `create'
    /app/lib/word_diff.rb:62:in `block (4 levels) in <class:WordDiff>'
    /app/lib/word_diff.rb:47:in `each'
    /app/lib/word_diff/document.rb:67:in `convert'
    /app/lib/word_diff.rb:49:in `each'
    /app/lib/word_diff.rb:46:in `each'
    /app/lib/word_diff.rb:46:in `block in <class:WordDiff>'
    /app/lib/word_diff.rb:49:in `block (3 levels) in <class:WordDiff>'
    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
    /app/lib/word_diff.rb:47:in `block (2 levels) in <class:WordDiff>'
```

Any chance of larger file support?

**Comment by benbalter** [comment]
@Razoxane The Gem could fall back to use the raw / blob endpoint, but that would fail for private repos. We'd have to shallow clone the entire repo to get private files larger than 1MB. If this is still an issue, would you be interested in / able to  adding a PR to fall back to the `raw.githubusercontent.com` version of the file?
